-- ============================================================
-- DB-driven sidebar menu: MENU_ITEM + MENU_ITEM_ACCESS tables
-- ============================================================

-- 1. Menu items table
CREATE TABLE MENU_ITEM (
    ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MENU_KEY        VARCHAR2(50)  NOT NULL UNIQUE,
    SECTION_LABEL   VARCHAR2(100),          -- NULL = no section header
    LABEL           VARCHAR2(100) NOT NULL,
    URL             VARCHAR2(255) NOT NULL,  -- relative path (appended to contextPath)
    ICON_CLASS      VARCHAR2(100),
    DISPLAY_ORDER   NUMBER        DEFAULT 0,
    IS_ACTIVE       NUMBER(1)     DEFAULT 1 CHECK (IS_ACTIVE IN (0, 1))
);

-- 2. Access rules table (no rows = visible to ALL)
--    ACCESS_TYPE:
--      DESIGNATION       – user's designation ID must equal ACCESS_VALUE
--      HIERARCHY_FROM    – user must be in the reporting chain above the designation in ACCESS_VALUE
--      DEPARTMENT        – user's DEPT must equal ACCESS_VALUE (case-insensitive)
--    Multiple rows for the same MENU_ITEM_ID are OR-ed.
CREATE TABLE MENU_ITEM_ACCESS (
    ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MENU_ITEM_ID    NUMBER        NOT NULL REFERENCES MENU_ITEM(ID),
    ACCESS_TYPE     VARCHAR2(30)  NOT NULL CHECK (ACCESS_TYPE IN ('DESIGNATION','HIERARCHY_FROM','DEPARTMENT')),
    ACCESS_VALUE    VARCHAR2(100) NOT NULL
);

-- ============================================================
-- Seed data  (matches the current hardcoded sidebar)
-- ============================================================

-- Dashboard (visible to all – no access rules)
INSERT INTO MENU_ITEM (MENU_KEY, SECTION_LABEL, LABEL, URL, ICON_CLASS, DISPLAY_ORDER)
VALUES ('dashboard', NULL, 'Dashboard', '/views/replacement/dashboard', 'fas fa-home', 10);

-- TEAM LEAD section  – designation 62
INSERT INTO MENU_ITEM (MENU_KEY, SECTION_LABEL, LABEL, URL, ICON_CLASS, DISPLAY_ORDER)
VALUES ('tl_approvals', 'TEAM LEAD', 'TL Approvals', '/views/replacement/tl/requestList', 'fas fa-clipboard-check', 20);

INSERT INTO MENU_ITEM_ACCESS (MENU_ITEM_ID, ACCESS_TYPE, ACCESS_VALUE)
VALUES ((SELECT ID FROM MENU_ITEM WHERE MENU_KEY = 'tl_approvals'), 'DESIGNATION', '62');

-- AM / CRO section  – designations 2, 4, 261
INSERT INTO MENU_ITEM (MENU_KEY, SECTION_LABEL, LABEL, URL, ICON_CLASS, DISPLAY_ORDER)
VALUES ('create_request', 'AM / CRO', 'Create Request', '/views/replacement/request?action=new', 'fas fa-plus-circle', 30);

INSERT INTO MENU_ITEM_ACCESS (MENU_ITEM_ID, ACCESS_TYPE, ACCESS_VALUE)
VALUES ((SELECT ID FROM MENU_ITEM WHERE MENU_KEY = 'create_request'), 'DESIGNATION', '2');
INSERT INTO MENU_ITEM_ACCESS (MENU_ITEM_ID, ACCESS_TYPE, ACCESS_VALUE)
VALUES ((SELECT ID FROM MENU_ITEM WHERE MENU_KEY = 'create_request'), 'DESIGNATION', '4');
INSERT INTO MENU_ITEM_ACCESS (MENU_ITEM_ID, ACCESS_TYPE, ACCESS_VALUE)
VALUES ((SELECT ID FROM MENU_ITEM WHERE MENU_KEY = 'create_request'), 'DESIGNATION', '261');

INSERT INTO MENU_ITEM (MENU_KEY, SECTION_LABEL, LABEL, URL, ICON_CLASS, DISPLAY_ORDER)
VALUES ('my_requests', 'AM / CRO', 'My Requests', '/views/replacement/request?action=myList', 'fas fa-list-alt', 40);

INSERT INTO MENU_ITEM_ACCESS (MENU_ITEM_ID, ACCESS_TYPE, ACCESS_VALUE)
VALUES ((SELECT ID FROM MENU_ITEM WHERE MENU_KEY = 'my_requests'), 'DESIGNATION', '2');
INSERT INTO MENU_ITEM_ACCESS (MENU_ITEM_ID, ACCESS_TYPE, ACCESS_VALUE)
VALUES ((SELECT ID FROM MENU_ITEM WHERE MENU_KEY = 'my_requests'), 'DESIGNATION', '4');
INSERT INTO MENU_ITEM_ACCESS (MENU_ITEM_ID, ACCESS_TYPE, ACCESS_VALUE)
VALUES ((SELECT ID FROM MENU_ITEM WHERE MENU_KEY = 'my_requests'), 'DESIGNATION', '261');

-- AM MANAGER section  – designation 87
INSERT INTO MENU_ITEM (MENU_KEY, SECTION_LABEL, LABEL, URL, ICON_CLASS, DISPLAY_ORDER)
VALUES ('commercial_approvals', 'AM MANAGER', 'Commercial Approvals', '/views/replacement/ammanager/requestList', 'fas fa-dollar-sign', 50);

INSERT INTO MENU_ITEM_ACCESS (MENU_ITEM_ID, ACCESS_TYPE, ACCESS_VALUE)
VALUES ((SELECT ID FROM MENU_ITEM WHERE MENU_KEY = 'commercial_approvals'), 'DESIGNATION', '87');

-- ACCOUNTS section  – designation 202
INSERT INTO MENU_ITEM (MENU_KEY, SECTION_LABEL, LABEL, URL, ICON_CLASS, DISPLAY_ORDER)
VALUES ('credit_note_approval', 'ACCOUNTS', 'Credit Note Approval', '/views/replacement/accounts/creditNoteApproval', 'fas fa-check-circle', 60);

INSERT INTO MENU_ITEM_ACCESS (MENU_ITEM_ID, ACCESS_TYPE, ACCESS_VALUE)
VALUES ((SELECT ID FROM MENU_ITEM WHERE MENU_KEY = 'credit_note_approval'), 'DESIGNATION', '202');

-- COURIER section  – hierarchy from designation 62 upward
INSERT INTO MENU_ITEM (MENU_KEY, SECTION_LABEL, LABEL, URL, ICON_CLASS, DISPLAY_ORDER)
VALUES ('courier_login', 'COURIER', 'Generate Courier Login', '/views/replacement/courier-login/page', 'fas fa-user-lock', 70);

INSERT INTO MENU_ITEM_ACCESS (MENU_ITEM_ID, ACCESS_TYPE, ACCESS_VALUE)
VALUES ((SELECT ID FROM MENU_ITEM WHERE MENU_KEY = 'courier_login'), 'HIERARCHY_FROM', '62');

-- LOGISTICS section
-- Pullback Management (visible to all)
INSERT INTO MENU_ITEM (MENU_KEY, SECTION_LABEL, LABEL, URL, ICON_CLASS, DISPLAY_ORDER)
VALUES ('pullback_mgmt', 'LOGISTICS', 'Pullback Management', '/views/replacement/logistics/pullbackManagement', 'fas fa-truck-loading', 80);

-- Courier Pincode Mapping – hierarchy from 87/62 OR dept LOGISTICS
INSERT INTO MENU_ITEM (MENU_KEY, SECTION_LABEL, LABEL, URL, ICON_CLASS, DISPLAY_ORDER)
VALUES ('courier_pincode', 'LOGISTICS', 'Courier Pincode Mapping', '/views/replacement/courier-pincode/page', 'fas fa-map-marker-alt', 90);

INSERT INTO MENU_ITEM_ACCESS (MENU_ITEM_ID, ACCESS_TYPE, ACCESS_VALUE)
VALUES ((SELECT ID FROM MENU_ITEM WHERE MENU_KEY = 'courier_pincode'), 'HIERARCHY_FROM', '87');
INSERT INTO MENU_ITEM_ACCESS (MENU_ITEM_ID, ACCESS_TYPE, ACCESS_VALUE)
VALUES ((SELECT ID FROM MENU_ITEM WHERE MENU_KEY = 'courier_pincode'), 'HIERARCHY_FROM', '62');
INSERT INTO MENU_ITEM_ACCESS (MENU_ITEM_ID, ACCESS_TYPE, ACCESS_VALUE)
VALUES ((SELECT ID FROM MENU_ITEM WHERE MENU_KEY = 'courier_pincode'), 'DEPARTMENT', 'LOGISTICS');

-- Replacement Register (visible to all)
INSERT INTO MENU_ITEM (MENU_KEY, SECTION_LABEL, LABEL, URL, ICON_CLASS, DISPLAY_ORDER)
VALUES ('replacement_register', NULL, 'Replacement Register', '/views/replacement/register', 'fas fa-book', 100);

COMMIT;
