-- =====================================================
-- OTP Management Table for Generic OTP Module
-- =====================================================
-- This table stores OTP state for pickup and other features.
-- Links to REPLACEMENT_PULLBACK via PULLBACK_ID (single FK).
-- All request context (callId, serialNo, reqId) is in REPLACEMENT_PULLBACK.

CREATE TABLE OTP_MANAGEMENT (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
        MINVALUE 1 MAXVALUE 9999999999999999999999999999 
        INCREMENT BY 1 START WITH 1 NOCACHE ORDER NOCYCLE 
        NOT NULL ENABLE PRIMARY KEY,
    
    -- Link to REPLACEMENT_PULLBACK
    PULLBACK_ID NUMBER NOT NULL,
    
    -- OTP data
    MOBILE_NUMBER VARCHAR2(20) NOT NULL,
    OTP_VALUE VARCHAR2(10),
    OTP_EXPIRY_TIME TIMESTAMP,
    
    -- Attempt and blocking management
    ATTEMPT_COUNT NUMBER DEFAULT 0,
    BLOCK_UNTIL_TIME TIMESTAMP,
    
    -- Validation tracking
    OTP_VALIDATED_AT TIMESTAMP,
    
    -- WhatsApp send status logging
    WA_SEND_STATUS VARCHAR2(500),
    
    -- Audit fields
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    
    -- Constraints
    CONSTRAINT UK_OTP_PULLBACK UNIQUE (PULLBACK_ID),
    CONSTRAINT CHK_OTP_ATTEMPT_COUNT CHECK (ATTEMPT_COUNT >= 0),
    CONSTRAINT CHK_OTP_ATTEMPT_COUNT_MAX CHECK (ATTEMPT_COUNT <= 5)
);

-- Index for faster lookups
CREATE INDEX IDX_OTP_PULLBACK ON OTP_MANAGEMENT(PULLBACK_ID);
CREATE INDEX IDX_OTP_EXPIRY ON OTP_MANAGEMENT(OTP_EXPIRY_TIME);

-- Comments for documentation
COMMENT ON TABLE OTP_MANAGEMENT IS 'Generic OTP management table for pickup and other features';
COMMENT ON COLUMN OTP_MANAGEMENT.PULLBACK_ID IS 'FK to REPLACEMENT_PULLBACK.ID';
COMMENT ON COLUMN OTP_MANAGEMENT.MOBILE_NUMBER IS 'Mobile number where OTP is sent';
COMMENT ON COLUMN OTP_MANAGEMENT.OTP_VALUE IS '4-digit OTP value (never returned in API response)';
COMMENT ON COLUMN OTP_MANAGEMENT.OTP_EXPIRY_TIME IS 'OTP expiry timestamp (5 minutes from generation)';
COMMENT ON COLUMN OTP_MANAGEMENT.ATTEMPT_COUNT IS 'Number of OTP generation attempts (max 5)';
COMMENT ON COLUMN OTP_MANAGEMENT.BLOCK_UNTIL_TIME IS 'Block timestamp if attempts exceeded (1 hour from last attempt)';
COMMENT ON COLUMN OTP_MANAGEMENT.OTP_VALIDATED_AT IS 'Timestamp when OTP was successfully validated';
COMMENT ON COLUMN OTP_MANAGEMENT.WA_SEND_STATUS IS 'WhatsApp send result (e.g. Message is submitted! or error details)';

COMMIT;

-- If table already exists, run this ALTER instead:
-- ALTER TABLE OTP_MANAGEMENT ADD WA_SEND_STATUS VARCHAR2(500);
-- COMMENT ON COLUMN OTP_MANAGEMENT.WA_SEND_STATUS IS 'WhatsApp send result (e.g. Message is submitted! or error details)';
