-- Audit tables and triggers (no AUD_BY)

-- CREDIT_NOTE
CREATE TABLE AUD_CREDIT_NOTE AS
SELECT * FROM CREDIT_NOTE WHERE 1=0;

ALTER TABLE AUD_CREDIT_NOTE ADD (
  AUD_ID NUMBER GENERATED ALWAYS AS IDENTITY,
  AUD_ACTION VARCHAR2(10),
  AUD_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP
);

CREATE OR REPLACE TRIGGER TRG_AUD_CREDIT_NOTE
AFTER INSERT OR UPDATE OR DELETE ON CREDIT_NOTE
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    INSERT INTO AUD_CREDIT_NOTE (
      ID, REPLACEMENT_REQUEST_ID, REPLACEMENT_PRINTER_DTL_ID, CREDIT_NOTE_NUMBER, LOCATION,
      MODEL_NAME, SERIAL_NO, ISSUE_DESCRIPTION, AGREEMENT_RATE, CREDIT_AMOUNT, COMMENTS,
      STATUS, DOCUMENT_PATH, CREATED_BY, CREATION_DATE_TIME, UPDATE_DATE_TIME,
      AUD_ACTION, AUD_AT
    ) VALUES (
      :NEW.ID, :NEW.REPLACEMENT_REQUEST_ID, :NEW.REPLACEMENT_PRINTER_DTL_ID, :NEW.CREDIT_NOTE_NUMBER, :NEW.LOCATION,
      :NEW.MODEL_NAME, :NEW.SERIAL_NO, :NEW.ISSUE_DESCRIPTION, :NEW.AGREEMENT_RATE, :NEW.CREDIT_AMOUNT, :NEW.COMMENTS,
      :NEW.STATUS, :NEW.DOCUMENT_PATH, :NEW.CREATED_BY, :NEW.CREATION_DATE_TIME, :NEW.UPDATE_DATE_TIME,
      'INSERT', SYSTIMESTAMP
    );
  ELSIF UPDATING THEN
    INSERT INTO AUD_CREDIT_NOTE (
      ID, REPLACEMENT_REQUEST_ID, REPLACEMENT_PRINTER_DTL_ID, CREDIT_NOTE_NUMBER, LOCATION,
      MODEL_NAME, SERIAL_NO, ISSUE_DESCRIPTION, AGREEMENT_RATE, CREDIT_AMOUNT, COMMENTS,
      STATUS, DOCUMENT_PATH, CREATED_BY, CREATION_DATE_TIME, UPDATE_DATE_TIME,
      AUD_ACTION, AUD_AT
    ) VALUES (
      :NEW.ID, :NEW.REPLACEMENT_REQUEST_ID, :NEW.REPLACEMENT_PRINTER_DTL_ID, :NEW.CREDIT_NOTE_NUMBER, :NEW.LOCATION,
      :NEW.MODEL_NAME, :NEW.SERIAL_NO, :NEW.ISSUE_DESCRIPTION, :NEW.AGREEMENT_RATE, :NEW.CREDIT_AMOUNT, :NEW.COMMENTS,
      :NEW.STATUS, :NEW.DOCUMENT_PATH, :NEW.CREATED_BY, :NEW.CREATION_DATE_TIME, :NEW.UPDATE_DATE_TIME,
      'UPDATE', SYSTIMESTAMP
    );
  ELSE
    INSERT INTO AUD_CREDIT_NOTE (
      ID, REPLACEMENT_REQUEST_ID, REPLACEMENT_PRINTER_DTL_ID, CREDIT_NOTE_NUMBER, LOCATION,
      MODEL_NAME, SERIAL_NO, ISSUE_DESCRIPTION, AGREEMENT_RATE, CREDIT_AMOUNT, COMMENTS,
      STATUS, DOCUMENT_PATH, CREATED_BY, CREATION_DATE_TIME, UPDATE_DATE_TIME,
      AUD_ACTION, AUD_AT
    ) VALUES (
      :OLD.ID, :OLD.REPLACEMENT_REQUEST_ID, :OLD.REPLACEMENT_PRINTER_DTL_ID, :OLD.CREDIT_NOTE_NUMBER, :OLD.LOCATION,
      :OLD.MODEL_NAME, :OLD.SERIAL_NO, :OLD.ISSUE_DESCRIPTION, :OLD.AGREEMENT_RATE, :OLD.CREDIT_AMOUNT, :OLD.COMMENTS,
      :OLD.STATUS, :OLD.DOCUMENT_PATH, :OLD.CREATED_BY, :OLD.CREATION_DATE_TIME, :OLD.UPDATE_DATE_TIME,
      'DELETE', SYSTIMESTAMP
    );
  END IF;
END;
/

-- REPLACEMENT_PRINTER_DETAILS
CREATE TABLE AUD_REP_PRINTER_DETAILS AS
SELECT * FROM REPLACEMENT_PRINTER_DETAILS WHERE 1=0;

ALTER TABLE AUD_REP_PRINTER_DETAILS ADD (
  AUD_ID NUMBER GENERATED ALWAYS AS IDENTITY,
  AUD_ACTION VARCHAR2(10),
  AUD_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP
);

CREATE OR REPLACE TRIGGER TRG_AUD_REP_PRINTER_DETAILS
AFTER INSERT OR UPDATE OR DELETE ON REPLACEMENT_PRINTER_DETAILS
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    INSERT INTO AUD_REP_PRINTER_DETAILS (
      ID, REPLACEMENT_REQUEST_ID, AGR_PROD_ID, EXISTING_P_MODEL_ID, CLIENT_DOT_ID,
      CONTACT_PERSON_NAME, CONTACT_PERSON_NUMBER, CONTACT_PERSON_EMAIL, EXISTING_SERIAL,
      NEW_P_MODEL_SELECTED_ID, NEW_P_MODEL_SELECTED_TEXT, NEW_P_MODEL_SOURCE, RECOMMENDED_COMMENTS,
      CREATION_DATE_TIME, UPDATE_DATE_TIME, PRINTER_TYPE, PAGE_COUNT, PAGE_COUNT_COMMENT,
      PRINTER_STAGE_ID, CONTINUE_EXISTING_COMMERCIAL, AM_COMMERCIAL_COMMENTS, PRINTER_ORDER_ITEM_ID,
      AUD_ACTION, AUD_AT
    ) VALUES (
      :NEW.ID, :NEW.REPLACEMENT_REQUEST_ID, :NEW.AGR_PROD_ID, :NEW.EXISTING_P_MODEL_ID, :NEW.CLIENT_DOT_ID,
      :NEW.CONTACT_PERSON_NAME, :NEW.CONTACT_PERSON_NUMBER, :NEW.CONTACT_PERSON_EMAIL, :NEW.EXISTING_SERIAL,
      :NEW.NEW_P_MODEL_SELECTED_ID, :NEW.NEW_P_MODEL_SELECTED_TEXT, :NEW.NEW_P_MODEL_SOURCE, :NEW.RECOMMENDED_COMMENTS,
      :NEW.CREATION_DATE_TIME, :NEW.UPDATE_DATE_TIME, :NEW.PRINTER_TYPE, :NEW.PAGE_COUNT, :NEW.PAGE_COUNT_COMMENT,
      :NEW.PRINTER_STAGE_ID, :NEW.CONTINUE_EXISTING_COMMERCIAL, :NEW.AM_COMMERCIAL_COMMENTS, :NEW.PRINTER_ORDER_ITEM_ID,
      'INSERT', SYSTIMESTAMP
    );
  ELSIF UPDATING THEN
    INSERT INTO AUD_REP_PRINTER_DETAILS (
      ID, REPLACEMENT_REQUEST_ID, AGR_PROD_ID, EXISTING_P_MODEL_ID, CLIENT_DOT_ID,
      CONTACT_PERSON_NAME, CONTACT_PERSON_NUMBER, CONTACT_PERSON_EMAIL, EXISTING_SERIAL,
      NEW_P_MODEL_SELECTED_ID, NEW_P_MODEL_SELECTED_TEXT, NEW_P_MODEL_SOURCE, RECOMMENDED_COMMENTS,
      CREATION_DATE_TIME, UPDATE_DATE_TIME, PRINTER_TYPE, PAGE_COUNT, PAGE_COUNT_COMMENT,
      PRINTER_STAGE_ID, CONTINUE_EXISTING_COMMERCIAL, AM_COMMERCIAL_COMMENTS, PRINTER_ORDER_ITEM_ID,
      AUD_ACTION, AUD_AT
    ) VALUES (
      :NEW.ID, :NEW.REPLACEMENT_REQUEST_ID, :NEW.AGR_PROD_ID, :NEW.EXISTING_P_MODEL_ID, :NEW.CLIENT_DOT_ID,
      :NEW.CONTACT_PERSON_NAME, :NEW.CONTACT_PERSON_NUMBER, :NEW.CONTACT_PERSON_EMAIL, :NEW.EXISTING_SERIAL,
      :NEW.NEW_P_MODEL_SELECTED_ID, :NEW.NEW_P_MODEL_SELECTED_TEXT, :NEW.NEW_P_MODEL_SOURCE, :NEW.RECOMMENDED_COMMENTS,
      :NEW.CREATION_DATE_TIME, :NEW.UPDATE_DATE_TIME, :NEW.PRINTER_TYPE, :NEW.PAGE_COUNT, :NEW.PAGE_COUNT_COMMENT,
      :NEW.PRINTER_STAGE_ID, :NEW.CONTINUE_EXISTING_COMMERCIAL, :NEW.AM_COMMERCIAL_COMMENTS, :NEW.PRINTER_ORDER_ITEM_ID,
      'UPDATE', SYSTIMESTAMP
    );
  ELSE
    INSERT INTO AUD_REP_PRINTER_DETAILS (
      ID, REPLACEMENT_REQUEST_ID, AGR_PROD_ID, EXISTING_P_MODEL_ID, CLIENT_DOT_ID,
      CONTACT_PERSON_NAME, CONTACT_PERSON_NUMBER, CONTACT_PERSON_EMAIL, EXISTING_SERIAL,
      NEW_P_MODEL_SELECTED_ID, NEW_P_MODEL_SELECTED_TEXT, NEW_P_MODEL_SOURCE, RECOMMENDED_COMMENTS,
      CREATION_DATE_TIME, UPDATE_DATE_TIME, PRINTER_TYPE, PAGE_COUNT, PAGE_COUNT_COMMENT,
      PRINTER_STAGE_ID, CONTINUE_EXISTING_COMMERCIAL, AM_COMMERCIAL_COMMENTS, PRINTER_ORDER_ITEM_ID,
      AUD_ACTION, AUD_AT
    ) VALUES (
      :OLD.ID, :OLD.REPLACEMENT_REQUEST_ID, :OLD.AGR_PROD_ID, :OLD.EXISTING_P_MODEL_ID, :OLD.CLIENT_DOT_ID,
      :OLD.CONTACT_PERSON_NAME, :OLD.CONTACT_PERSON_NUMBER, :OLD.CONTACT_PERSON_EMAIL, :OLD.EXISTING_SERIAL,
      :OLD.NEW_P_MODEL_SELECTED_ID, :OLD.NEW_P_MODEL_SELECTED_TEXT, :OLD.NEW_P_MODEL_SOURCE, :OLD.RECOMMENDED_COMMENTS,
      :OLD.CREATION_DATE_TIME, :OLD.UPDATE_DATE_TIME, :OLD.PRINTER_TYPE, :OLD.PAGE_COUNT, :OLD.PAGE_COUNT_COMMENT,
      :OLD.PRINTER_STAGE_ID, :OLD.CONTINUE_EXISTING_COMMERCIAL, :OLD.AM_COMMERCIAL_COMMENTS, :OLD.PRINTER_ORDER_ITEM_ID,
      'DELETE', SYSTIMESTAMP
    );
  END IF;
END;
/

-- REPLACEMENT_PULLBACK
CREATE TABLE AUD_REPLACEMENT_PULLBACK AS
SELECT * FROM REPLACEMENT_PULLBACK WHERE 1=0;

ALTER TABLE AUD_REPLACEMENT_PULLBACK ADD (
  AUD_ID NUMBER GENERATED ALWAYS AS IDENTITY,
  AUD_ACTION VARCHAR2(10),
  AUD_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP
);

CREATE OR REPLACE TRIGGER TRG_AUD_REPLACEMENT_PULLBACK
AFTER INSERT OR UPDATE OR DELETE ON REPLACEMENT_PULLBACK
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    INSERT INTO AUD_REPLACEMENT_PULLBACK (
      ID, REPLACEMENT_REQ_ID, CALL_ID, CLIENT_DOT_ID, LOCATION, P_MODEL, P_SERIAL_NO,
      PICKED_BY, STATUS, COURIER_ID, COURIER_NAME, CONSIGNMENT_NO, DISPATCH_DATE, ARRIVAL_DATE,
      RECEIPT, DESTINATION_BRANCH, TRANSPORT_MODE, CONTACT_PERSON, CONTACT_NUMBER, COMMENTS,
      PRINTER, POWER_CABLE, LAN_CABLE, TRAY, EMPTY_CARTRIDGE, UNUSED_CARTRIDGE, PULLBACK_MODE,
      REPLACEMENT_PRINTER_DETAILS_ID,
      AUD_ACTION, AUD_AT
    ) VALUES (
      :NEW.ID, :NEW.REPLACEMENT_REQ_ID, :NEW.CALL_ID, :NEW.CLIENT_DOT_ID, :NEW.LOCATION, :NEW.P_MODEL, :NEW.P_SERIAL_NO,
      :NEW.PICKED_BY, :NEW.STATUS, :NEW.COURIER_ID, :NEW.COURIER_NAME, :NEW.CONSIGNMENT_NO, :NEW.DISPATCH_DATE, :NEW.ARRIVAL_DATE,
      :NEW.RECEIPT, :NEW.DESTINATION_BRANCH, :NEW.TRANSPORT_MODE, :NEW.CONTACT_PERSON, :NEW.CONTACT_NUMBER, :NEW.COMMENTS,
      :NEW.PRINTER, :NEW.POWER_CABLE, :NEW.LAN_CABLE, :NEW.TRAY, :NEW.EMPTY_CARTRIDGE, :NEW.UNUSED_CARTRIDGE, :NEW.PULLBACK_MODE,
      :NEW.REPLACEMENT_PRINTER_DETAILS_ID,
      'INSERT', SYSTIMESTAMP
    );
  ELSIF UPDATING THEN
    INSERT INTO AUD_REPLACEMENT_PULLBACK (
      ID, REPLACEMENT_REQ_ID, CALL_ID, CLIENT_DOT_ID, LOCATION, P_MODEL, P_SERIAL_NO,
      PICKED_BY, STATUS, COURIER_ID, COURIER_NAME, CONSIGNMENT_NO, DISPATCH_DATE, ARRIVAL_DATE,
      RECEIPT, DESTINATION_BRANCH, TRANSPORT_MODE, CONTACT_PERSON, CONTACT_NUMBER, COMMENTS,
      PRINTER, POWER_CABLE, LAN_CABLE, TRAY, EMPTY_CARTRIDGE, UNUSED_CARTRIDGE, PULLBACK_MODE,
      REPLACEMENT_PRINTER_DETAILS_ID,
      AUD_ACTION, AUD_AT
    ) VALUES (
      :NEW.ID, :NEW.REPLACEMENT_REQ_ID, :NEW.CALL_ID, :NEW.CLIENT_DOT_ID, :NEW.LOCATION, :NEW.P_MODEL, :NEW.P_SERIAL_NO,
      :NEW.PICKED_BY, :NEW.STATUS, :NEW.COURIER_ID, :NEW.COURIER_NAME, :NEW.CONSIGNMENT_NO, :NEW.DISPATCH_DATE, :NEW.ARRIVAL_DATE,
      :NEW.RECEIPT, :NEW.DESTINATION_BRANCH, :NEW.TRANSPORT_MODE, :NEW.CONTACT_PERSON, :NEW.CONTACT_NUMBER, :NEW.COMMENTS,
      :NEW.PRINTER, :NEW.POWER_CABLE, :NEW.LAN_CABLE, :NEW.TRAY, :NEW.EMPTY_CARTRIDGE, :NEW.UNUSED_CARTRIDGE, :NEW.PULLBACK_MODE,
      :NEW.REPLACEMENT_PRINTER_DETAILS_ID,
      'UPDATE', SYSTIMESTAMP
    );
  ELSE
    INSERT INTO AUD_REPLACEMENT_PULLBACK (
      ID, REPLACEMENT_REQ_ID, CALL_ID, CLIENT_DOT_ID, LOCATION, P_MODEL, P_SERIAL_NO,
      PICKED_BY, STATUS, COURIER_ID, COURIER_NAME, CONSIGNMENT_NO, DISPATCH_DATE, ARRIVAL_DATE,
      RECEIPT, DESTINATION_BRANCH, TRANSPORT_MODE, CONTACT_PERSON, CONTACT_NUMBER, COMMENTS,
      PRINTER, POWER_CABLE, LAN_CABLE, TRAY, EMPTY_CARTRIDGE, UNUSED_CARTRIDGE, PULLBACK_MODE,
      REPLACEMENT_PRINTER_DETAILS_ID,
      AUD_ACTION, AUD_AT
    ) VALUES (
      :OLD.ID, :OLD.REPLACEMENT_REQ_ID, :OLD.CALL_ID, :OLD.CLIENT_DOT_ID, :OLD.LOCATION, :OLD.P_MODEL, :OLD.P_SERIAL_NO,
      :OLD.PICKED_BY, :OLD.STATUS, :OLD.COURIER_ID, :OLD.COURIER_NAME, :OLD.CONSIGNMENT_NO, :OLD.DISPATCH_DATE, :OLD.ARRIVAL_DATE,
      :OLD.RECEIPT, :OLD.DESTINATION_BRANCH, :OLD.TRANSPORT_MODE, :OLD.CONTACT_PERSON, :OLD.CONTACT_NUMBER, :OLD.COMMENTS,
      :OLD.PRINTER, :OLD.POWER_CABLE, :OLD.LAN_CABLE, :OLD.TRAY, :OLD.EMPTY_CARTRIDGE, :OLD.UNUSED_CARTRIDGE, :OLD.PULLBACK_MODE,
      :OLD.REPLACEMENT_PRINTER_DETAILS_ID,
      'DELETE', SYSTIMESTAMP
    );
  END IF;
END;
/

-- REPLACEMENT_REQUEST
CREATE TABLE AUD_REPLACEMENT_REQUEST AS
SELECT * FROM REPLACEMENT_REQUEST WHERE 1=0;

ALTER TABLE AUD_REPLACEMENT_REQUEST ADD (
  AUD_ID NUMBER GENERATED ALWAYS AS IDENTITY,
  AUD_ACTION VARCHAR2(10),
  AUD_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP
);

CREATE OR REPLACE TRIGGER TRG_AUD_REPLACEMENT_REQUEST
AFTER INSERT OR UPDATE OR DELETE ON REPLACEMENT_REQUEST
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    INSERT INTO AUD_REPLACEMENT_REQUEST (
      ID, REPLACEMENT_REASON_ID, CLIENT_DOT_ID_SIGNING, REPLACEMENT_TYPE, REQUESTER_USER_ID,
      SERVICE_CALL_ID, CONTACT_PERSON_NAME, CONTACT_PERSON_NUMBER, CONTACT_PERSON_EMAIL,
      IS_EDITABLE, CURRENT_STAGE, CURRENT_OWNER_ID, SOURCE, STATUS, CREATION_DATE_TIME,
      UPDATE_DATE_TIME, SIGNED_LETTER_PATH, SIGNED_UPLOAD_DATE, PRINTER_ORDER_ID,
      REPLACEMENT_LETTER_GENERATED,
      AUD_ACTION, AUD_AT
    ) VALUES (
      :NEW.ID, :NEW.REPLACEMENT_REASON_ID, :NEW.CLIENT_DOT_ID_SIGNING, :NEW.REPLACEMENT_TYPE, :NEW.REQUESTER_USER_ID,
      :NEW.SERVICE_CALL_ID, :NEW.CONTACT_PERSON_NAME, :NEW.CONTACT_PERSON_NUMBER, :NEW.CONTACT_PERSON_EMAIL,
      :NEW.IS_EDITABLE, :NEW.CURRENT_STAGE, :NEW.CURRENT_OWNER_ID, :NEW.SOURCE, :NEW.STATUS, :NEW.CREATION_DATE_TIME,
      :NEW.UPDATE_DATE_TIME, :NEW.SIGNED_LETTER_PATH, :NEW.SIGNED_UPLOAD_DATE, :NEW.PRINTER_ORDER_ID,
      :NEW.REPLACEMENT_LETTER_GENERATED,
      'INSERT', SYSTIMESTAMP
    );
  ELSIF UPDATING THEN
    INSERT INTO AUD_REPLACEMENT_REQUEST (
      ID, REPLACEMENT_REASON_ID, CLIENT_DOT_ID_SIGNING, REPLACEMENT_TYPE, REQUESTER_USER_ID,
      SERVICE_CALL_ID, CONTACT_PERSON_NAME, CONTACT_PERSON_NUMBER, CONTACT_PERSON_EMAIL,
      IS_EDITABLE, CURRENT_STAGE, CURRENT_OWNER_ID, SOURCE, STATUS, CREATION_DATE_TIME,
      UPDATE_DATE_TIME, SIGNED_LETTER_PATH, SIGNED_UPLOAD_DATE, PRINTER_ORDER_ID,
      REPLACEMENT_LETTER_GENERATED,
      AUD_ACTION, AUD_AT
    ) VALUES (
      :NEW.ID, :NEW.REPLACEMENT_REASON_ID, :NEW.CLIENT_DOT_ID_SIGNING, :NEW.REPLACEMENT_TYPE, :NEW.REQUESTER_USER_ID,
      :NEW.SERVICE_CALL_ID, :NEW.CONTACT_PERSON_NAME, :NEW.CONTACT_PERSON_NUMBER, :NEW.CONTACT_PERSON_EMAIL,
      :NEW.IS_EDITABLE, :NEW.CURRENT_STAGE, :NEW.CURRENT_OWNER_ID, :NEW.SOURCE, :NEW.STATUS, :NEW.CREATION_DATE_TIME,
      :NEW.UPDATE_DATE_TIME, :NEW.SIGNED_LETTER_PATH, :NEW.SIGNED_UPLOAD_DATE, :NEW.PRINTER_ORDER_ID,
      :NEW.REPLACEMENT_LETTER_GENERATED,
      'UPDATE', SYSTIMESTAMP
    );
  ELSE
    INSERT INTO AUD_REPLACEMENT_REQUEST (
      ID, REPLACEMENT_REASON_ID, CLIENT_DOT_ID_SIGNING, REPLACEMENT_TYPE, REQUESTER_USER_ID,
      SERVICE_CALL_ID, CONTACT_PERSON_NAME, CONTACT_PERSON_NUMBER, CONTACT_PERSON_EMAIL,
      IS_EDITABLE, CURRENT_STAGE, CURRENT_OWNER_ID, SOURCE, STATUS, CREATION_DATE_TIME,
      UPDATE_DATE_TIME, SIGNED_LETTER_PATH, SIGNED_UPLOAD_DATE, PRINTER_ORDER_ID,
      REPLACEMENT_LETTER_GENERATED,
      AUD_ACTION, AUD_AT
    ) VALUES (
      :OLD.ID, :OLD.REPLACEMENT_REASON_ID, :OLD.CLIENT_DOT_ID_SIGNING, :OLD.REPLACEMENT_TYPE, :OLD.REQUESTER_USER_ID,
      :OLD.SERVICE_CALL_ID, :OLD.CONTACT_PERSON_NAME, :OLD.CONTACT_PERSON_NUMBER, :OLD.CONTACT_PERSON_EMAIL,
      :OLD.IS_EDITABLE, :OLD.CURRENT_STAGE, :OLD.CURRENT_OWNER_ID, :OLD.SOURCE, :OLD.STATUS, :OLD.CREATION_DATE_TIME,
      :OLD.UPDATE_DATE_TIME, :OLD.SIGNED_LETTER_PATH, :OLD.SIGNED_UPLOAD_DATE, :OLD.PRINTER_ORDER_ID,
      :OLD.REPLACEMENT_LETTER_GENERATED,
      'DELETE', SYSTIMESTAMP
    );
  END IF;
END;
/
