SELECT p.ID, p.REPLACEMENT_REQ_ID, p.CALL_ID, p.CLIENT_DOT_ID, p.LOCATION,
       p.P_MODEL, p.P_SERIAL_NO, p.PICKED_BY, tpm.DESCRIPTION as STATUS,p.status ,p.COURIER_ID,
       p.COURIER_NAME, p.CONSIGNMENT_NO, p.DISPATCH_DATE, p.ARRIVAL_DATE,
       p.RECEIPT, p.DESTINATION_BRANCH, p.TRANSPORT_MODE, p.CONTACT_PERSON,
       p.CONTACT_NUMBER, p.COMMENTS, p.PRINTER, p.POWER_CABLE, p.LAN_CABLE,
       p.TRAY, p.EMPTY_CARTRIDGE,
       poi.CART_PICKUP_QUANITY AS UNUSED_CARTRIDGE,
       p.PULLBACK_MODE,
       p.REPLACEMENT_PRINTER_DETAILS_ID,
       c.NAME AS CLIENT_NAME,
       pm.MODEL_NAME AS PRINTER_MODEL_NAME,
       'REQ-' || LPAD(p.REPLACEMENT_REQ_ID, 4, '0') AS REPLACEMENT_REQ_NO
FROM REPLACEMENT_PULLBACK p
         LEFT JOIN TAT_PRINTER_MASTER TPM on p.STATUS=tpm.ID
         LEFT JOIN CLIENT c ON c.ID = p.CLIENT_DOT_ID
         LEFT JOIN P_MODEL pm ON pm.ID = p.P_MODEL
         LEFT JOIN REPLACEMENT_PRINTER_DETAILS rpd ON rpd.ID = p.REPLACEMENT_PRINTER_DETAILS_ID
         LEFT JOIN PRINTER_ORDER_ITEM poi ON poi.ID = rpd.PRINTER_ORDER_ITEM_ID
WHERE 1=1


SELECT * FROM REPLACEMENT_PULLBACK where P_SERIAL_NO='CNCXH3CBP8' and REPLACEMENT_REQ_ID=544



select * from TAT_PRINTER_MASTER